name: Publish Docker Image

on:
  push:
    branches:
      - main  # 或您的默认分支名
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.password }}" | docker login -u "${{ secrets.user }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t xznwwh/old:latest .
        docker push xznwwh/old:latest

    - name: Delete old workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repository: ${{ github.repository }}
        older-than-seconds: 3600
